### ISSUE TITLE
ran into issue running first_run_dbt_project_and_profiles_fixer.py

### ISSUE THREAD

**Issue by Frydafly** [bsd/dbt-arc-functions#75] opened 2022-10-04 20:02 UTC
<img width="805" alt="Screen Shot 2022-10-04 at 3 02 52 PM" src="https://user-images.githubusercontent.com/22733009/193914629-1cfe3f4f-cf3f-4507-af6c-0ed9d684cfd6.png">

context: running `first_run_dbt_project_and_profiles_fixer.py` on `bsd-msf-dbt` using main branch of `dbt-arc-functions`

see above error

@ryantimjohn any ideas?

**Comment by Frydafly** [comment] 2022-10-04 20:08
given bsd-msf-dbt isn't a new profile, I skipped on over to create or update standard models and modified the packages.yml to pull from dbt-arc-functions and am not blocked, but still wanted to flag the above.

**Comment by ryantimjohn** [comment] 2022-10-05 00:54
@Frydafly Thank you! Will try and reproduce and check into this. I'm wondering if something came up with loading the yaml.

**Comment by Frydafly** [comment] 2022-10-05 17:35
@ryantimjohn a note that this worked for habitat

**Comment by ryantimjohn** [comment] 2022-10-11 21:55
<img width="1149" alt="Screen Shot 2022-10-11 at 5 55 06 PM" src="https://user-images.githubusercontent.com/16624855/195205524-75d48357-4b6c-4fb3-b529-9a1895a3ebdc.png">
@fryda I don't know what's up but I've tried this on a few projects but am unable to reproduce the error

**Comment by ryantimjohn** [comment] 2022-10-11 21:57
I wonder if this was a one-time thing or maybe that the yaml decoder wasn't working properly. One way or another, do you mind if we close this out and reopen if it recurrs?

**Closed** 2022-10-11 21:57 UTC
Labels: bug
